language: go
go:
  - 1.4
  - tip
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bzr mercurial -qq
install:
  - go get -d -t github.com/tsuru/mongoapi
script:
  - go test github.com/tsuru/mongoapi
services: mongodb
