language: go
go:
  - 1.4
  - tip
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bzr mercurial -qq
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get github.com/tools/godep
  - go get -d -t
  - godep restore
script:
  - go test
services: mongodb
