language: go
sudo: false
go:
  - 1.4
  - 1.5
  - tip
install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get github.com/tools/godep
  - go get -d -t
  - godep restore
script:
  - go test
services: mongodb
